### ISSUE TITLE
Move "People" data to a dedicated file

### ISSUE THREAD

**Issue by nicolaerario** [AndreaErario/compleanninator#2]
What do you think about to manage 'PEOPLE' data with a real (tracked) Json file instead to use a (untracked) dotenv file?
I think can be better to use the dotenv file only for secrets and things like that and to have a specific file to handle data.

**Comment by AndreaErario** [comment]
Thanks for the feedback! I decided to move the people data from the dotenv to a database since I'm hosting this program on Heroku. You can see 692672d793d197c4786d5f67abb6ad88e16e4923
